### ISSUE TITLE
aria-invalid on checkboxes and radio groups

### ISSUE THREAD

**Issue by yankeyhotel** [CodyHouse/cd-choice-buttons-changelog#2]
I just ran into this and read about it. Looks like it can be a little weird to set aria-invalid on checkboxes and radio groups. How does it work on CodyHouse?

https://blog.tenon.io/accessible-validation-of-checkbox-and-radiobutton-groups/

**Comment by sebastiano-guerriero** [comment]
Hi! We don't use aria-invalid in this component. We use a native checkbox as fallback for users using assistive technologies, and a custom checkbox with aria-hidden="true" for all the other users. Cheers
